# Simple workflow for deploying static content to GitHub Pages
name: Deploy content

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install packages
        run: |
          npm install
      - name: Build pages
        run: |
          npm run build
      - name: Publish pages
        run: |
          cat > publishkey <<EOF
          ${{ secrets.PUBLISH_SSH_KEY }}
          EOF
          chmod 600 publishkey
          rsync -rv -e "ssh -i publishkey -o stricthostkeychecking=no" _site/ pgs.sh:www-larsshack/
